---
dir: rtl
---
# بررسی 

## توضیح راجب دیتاست
این دیتاست یک مشکل classification دارد که هر سطر آن نشان دهنده یک مشاهده است که در ستون آخر آن ما با لیبل یا Target داریم که دو وضعیت M یعنی Mines یا نشان دهنده مین هست 
یا R که نشان دهنده وجود سنگ می باشد.



### چیزایی که یاد گرفتم:

- **در پایتون:**
    - وقتی دیتاستی داریم که هیچ سطر و ستونی براش تعریف نشده می تونیم در pandas زمانی که داریم از pd.read_csv() استفاده میکنیم درون پرانتز از پارامتر header = None استفاده کنیم. از همین روش دیگر سطر اول را به عنوان نام ستون ها نمی گیرد بلکه از اعداد طبیعی برای نامگذاری استفاده می کند.

- **در یادگیری ماشین:**
    - زمانی که دیتاست با سطرهای کمی داریم به طور کلی نمی شود از مدلهای پیچیده مانند RandomForest یا XGboost استفاده کرد و مدل هایی مانند LogisticRegression ، SVM می توانند به خوبی کار کنند
    - گاهی اوقات به جای اینکه خالی بزارند جای داده های گمشده رو اونها رو با اعداد خیلی بزرگ یا خیلی کوچیک پر میکنند تا مشکلی در کد ایجاد نشه به همین دلیل ما نیاز داریم که اول این مشکل رو پیدا کنیم و کارهایی که نیاز هست رو روی این نوع داده ها انجام بدیم.
    